AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'db/migrate/**/*.rb'
    - 'db/seed_data/**/*.rb'
    - 'db/seeders/**/*.rb'
    - 'db/seeds.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'Brewfile'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'

Style/NumericPredicate:
  EnforcedStyle: comparison

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/DotPosition:
  EnforcedStyle: trailing

Lint/UnusedBlockArgument:
  Enabled: true

Metrics/AbcSize:
  Max: 35

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
    - benchmark

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 3

Style/WordArray:
  MinSize: 3

Metrics/BlockLength:
  Exclude:
    - 'app/rails_admin_models/*.rb'
    - 'app/views/**/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*'

Bundler/OrderedGems:
  Enabled: false